name: Mathsismagic
on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout the files 
      uses: actions/checkout@v3
    - name: Setting nodejs Environment
      uses: actions/setup-node@v3.3.0
     
    - name: npm install and npm build
      run: |
        npm install
        pwd
        
    - name: parent working directory
      run: pwd
        
    - name: copy Build files to EC2
      uses: garygrossgarten/github-action-scp@release
      with: 
       local: /home/runner/work/mathsismagic/mathsismagic
       remote: /var/www/html/
       host: 54.208.12.15 
       username: ubuntu
       password: 687347
       
       
       
       
       
       
       
       
       
